substitutions:
  device_id: sensecap_d1s_01
  device_name: sensecap-d1s
  friendly_name: SenseCAP Indicator
  site_id: home1

packages:
  profile: !include packages/sensecap_next/profile_minimal.yaml
  device_profile: !include devices/sensecap_d1s_01/device_profile.yaml
