# SenseCAP Indicator sensors + wifi info text
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Wi-Fi IP Address"
      id: ip_sensor
      entity_category: diagnostic
    ssid:
      name: "Wi-Fi SSID"
      id: ssid_sensor
      entity_category: diagnostic
    bssid:
      name: "Wi-Fi BSSID"
      id: bssid_sensor
      entity_category: diagnostic

  - platform: version
    name: "ESPHome Version"
    id: esphome_version_txt
    hide_timestamp: true
    entity_category: diagnostic

  - platform: template
    name: "ESP Reset Reason"
    id: esp_reset_reason_txt
    entity_category: diagnostic
    update_interval: 30s
    lambda: |-
      switch (esp_reset_reason()) {
        case ESP_RST_POWERON: return std::string("Power On");
        case ESP_RST_EXT: return std::string("External");
        case ESP_RST_SW: return std::string("Software");
        case ESP_RST_PANIC: return std::string("Panic");
        case ESP_RST_INT_WDT: return std::string("Int WDT");
        case ESP_RST_TASK_WDT: return std::string("Task WDT");
        case ESP_RST_WDT: return std::string("WDT");
        case ESP_RST_DEEPSLEEP: return std::string("Deep Sleep");
        case ESP_RST_BROWNOUT: return std::string("Brownout");
        case ESP_RST_SDIO: return std::string("SDIO");
        default: return std::string("Unknown");
      }

sensor:
  - platform: packet_transport # from RP2040 0x59
    provider: d1-rp2040
    id: voc
    name: "VOC Index"
    internal: false
    accuracy_decimals: 0
    icon: "mdi:weather-dust"
    device_class: aqi
    on_value:
      then:
        - lambda: 'id(rp2040_last_seen_ms) = millis();'

  - platform: packet_transport  # from RP2040 0x62
    provider: d1-rp2040
    id: co2
    name: "CO2"
    internal: false
    accuracy_decimals: 0
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    device_class: carbon_dioxide
    on_value:
      then:
        - lambda: 'id(rp2040_last_seen_ms) = millis();'

  - platform: packet_transport
    provider: d1-rp2040
    id: temp
    name: "Temperature"
    internal: false
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    unit_of_measurement: "C"
    device_class: temperature
    on_value:
      then:
        - lambda: 'id(rp2040_last_seen_ms) = millis();'

  - platform: packet_transport
    provider: d1-rp2040
    id: humid
    name: "Humidity"
    internal: false
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    device_class: humidity
    on_value:
      then:
        - lambda: 'id(rp2040_last_seen_ms) = millis();'

  # --- INTERNAL TEMPERATURE + UPTIME ---
  - platform: internal_temperature
    id: internal_temp
    name: "ESP Internal Temp"
    update_interval: 30s
    entity_category: diagnostic

  - platform: uptime
    id: uptime_sensor
    name: "ESP Uptime"
    update_interval: 10s
    entity_category: diagnostic

  - platform: wifi_signal
    name: "Wi-Fi Signal"
    id: wi_fi_signal
    update_interval: 30s
    entity_category: diagnostic

  # --- BOARD/CHIP DIAGNOSTICS ---
  - platform: template
    name: "ESP CPU Frequency"
    id: esp_cpu_freq_mhz
    unit_of_measurement: "MHz"
    accuracy_decimals: 0
    entity_category: diagnostic
    update_interval: 60s
    lambda: |-
      return 160.0f;

  - platform: template
    name: "ESP Flash Size"
    id: esp_flash_size_mb
    unit_of_measurement: "MB"
    accuracy_decimals: 0
    entity_category: diagnostic
    update_interval: 300s
    lambda: |-
      return 8.0f;

  - platform: template
    name: "PSRAM Total"
    id: esp_psram_total_kb
    unit_of_measurement: "KB"
    accuracy_decimals: 0
    entity_category: diagnostic
    update_interval: 120s
    lambda: |-
      return (float) (heap_caps_get_total_size(MALLOC_CAP_SPIRAM) / 1024);

  - platform: template
    name: "PSRAM Free"
    id: esp_psram_free_kb
    unit_of_measurement: "KB"
    accuracy_decimals: 0
    entity_category: diagnostic
    update_interval: 15s
    lambda: |-
      return (float) (heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024);

  - platform: template
    name: "RP2040 Last Seen"
    id: rp2040_last_seen_s
    unit_of_measurement: "s"
    accuracy_decimals: 0
    entity_category: diagnostic
    update_interval: 5s
    lambda: |-
      if (id(rp2040_last_seen_ms) == 0) return NAN;
      return (float) ((millis() - id(rp2040_last_seen_ms)) / 1000);

  # Example HA Sensors (imported from Home Assistant)
  - platform: homeassistant
    id: ha_outdoor_temp
    entity_id: sensor.outdoor_temperature  # Replace with actual
    name: "Outdoor Temperature"
