# SenseCAP Indicator inputs + factory reset
button:
  - platform: factory_reset
    id: factory_reset_btn
    name: "Factory Reset"
    internal: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO38
      inverted: true
    name: "User Button"
    id: user_button
    on_multi_click:
      - timing:
          - ON for 10s to 20s
          - OFF for at least 50ms
        then:
          - button.press: factory_reset_btn

      - timing:
          - ON for 3s to 9s
          - OFF for at least 50ms
        then:
          - if:
              condition:
                lambda: 'return !id(screen_off);'
              then:
                - lvgl.pause:
                - light.turn_off: backlight
                - lambda: 'id(screen_off) = true;'

      - timing:
          - ON for 50ms to 500ms
          - OFF for at least 50ms
        then:
          - if:
              condition:
                lambda: 'return id(screen_off);'
              then:
                - lvgl.resume:
                - script.execute: apply_display_brightness
                - lambda: |-
                    id(screen_off) = false;
                    id(last_interaction_ms) = millis();
                    id(last_auto_scroll_ms) = id(last_interaction_ms);
                    id(scroll_sleep_start_ms) = 0;
                    id(nav_page_index) = 0;
                - script.execute: nav_show_home_user



