external_components:
  - source:
      type: local
      path: custom_components
#  - source:
 #     type: local
  #    path: esphome

#- source:
 #     type: git
  #    url: https://github.com/Bigbassmann/esphome-custom-wifi-tx-power.git
   #   ref: main
    #  path: esphome  

#- source: github://Bigbassmann/esphome-custom-wifi-tx-power@main

#github://Bigbassmann/esphome-custom-wifi-tx-power@main#esphome
      #type: git
      #url: https://github.com/Bigbassmann/esphome-custom-wifi-tx-power.git
      #ref: main
      #type: local
      # path:  #custom_components/wifi_tx_power

#external_components:
 # - source: 
#github://Bigbassmann/esphome-custom-wifi-tx-power@main#esphome/components/wifi_tx_power
#github://Bigbassmann/esphome-custom-wifi-tx-power@main#esphome
#github://Bigbassmann/esphome-custom-wifi-tx-power@main#esphome/components
#github://Bigbassmann/esphome-custom-wifi-tx-power@main
#github://Bigbassmann/esphome-custom-wifi-tx-power@main#components/wifi_tx_power
# github://Bigbassmann/esphome-custom-wifi-tx-power@main#wifi_tx_power
      #type: local
      # path:  #custom_components/wifi_tx_power

text_sensor:
  - platform: template
    name: "${device_name} ESP Reset Reason"
    id: esp_reset_reason_text
    entity_category: diagnostic
    lambda: |-
      switch (esp_reset_reason()) {
        case ESP_RST_UNKNOWN:     return {"Unknown"};
        case ESP_RST_POWERON:     return {"Power On"};
        case ESP_RST_EXT:         return {"External Reset"};
        case ESP_RST_SW:          return {"Software Reset"};
        case ESP_RST_PANIC:       return {"Panic"};
        case ESP_RST_INT_WDT:     return {"Interrupt WDT"};
        case ESP_RST_TASK_WDT:    return {"Task WDT"};
        case ESP_RST_WDT:         return {"Other WDT"};
        case ESP_RST_DEEPSLEEP:   return {"Deep Sleep Wake"};
        case ESP_RST_BROWNOUT:    return {"Brownout"};
        case ESP_RST_SDIO:        return {"SDIO"};
        case ESP_RST_USB:         return {"USB"};
        case ESP_RST_JTAG:        return {"JTAG"};
        case ESP_RST_EFUSE:       return {"Efuse"};
        case ESP_RST_PWR_GLITCH:  return {"Power Glitch"};
        case ESP_RST_CPU_LOCKUP:  return {"CPU Lockup"};
        default:                  return {"Unknown"};
      }
    update_interval: never
    
select:
  - platform: template
    name: "${device_name} Logger Level"
    id: logger_level_select
    optimistic: true
    restore_value: true
    options:
      - "NONE"
      - "ERROR"
      - "WARN"
      - "INFO"
      - "DEBUG"
      - "VERBOSE"
      - "VERY_VERBOSE"
    initial_option: "VERBOSE"  # Default
    on_value:
      - lambda: |-
          std::string opt = x;
          int level = ESPHOME_LOG_LEVEL_VERBOSE;  // Default
          if (opt == "NONE") level = ESPHOME_LOG_LEVEL_NONE;
          else if (opt == "ERROR") level = ESPHOME_LOG_LEVEL_ERROR;
          else if (opt == "WARN") level = ESPHOME_LOG_LEVEL_WARN;
          else if (opt == "INFO") level = ESPHOME_LOG_LEVEL_INFO;
          else if (opt == "DEBUG") level = ESPHOME_LOG_LEVEL_DEBUG;
          else if (opt == "VERBOSE") level = ESPHOME_LOG_LEVEL_VERBOSE;
          else if (opt == "VERY_VERBOSE") level = ESPHOME_LOG_LEVEL_VERY_VERBOSE;
          esphome::logger::global_logger->set_log_level(level);
          ESP_LOGI("config", "Logger level set to %s", opt.c_str());

  - platform: wifi_tx_power
    name: "${device_name} WiFi Output Power"
    id: wifi_power_level_select
    optimistic: true
    restore_value: true
    options:
      - "20.0" #Default/max for ESP32; good range but higher power draw.
      - "19.5" #High power; common for strong signals.
      - "19.0" #Slightly reduced; balances range and efficiency.
      - "18.5" #Moderate; useful for indoor setups.
      - "18.0"
      - "17.5"
      - "17.0" #Lower power; reduces interference.
      - "16.5"
      - "16.0"
      - "15.5"
      - "15.0" #Even lower; for battery optimization.
      - "14.5"
      - "14.0"
      - "13.5"
      - "13.0" #Reduced range; energy-efficient.
      - "12.5"
      - "12.0"
      - "11.5"
      - "11.0" #Minimal range; very low power.
      - "10.5"
      - "10.0"
      - "9.5"
      - "9.0"
      - "8.5" #Minimum practical; shortest range, lowest consumption.
    initial_option: "20.0"
               
sensor:
  - platform: template
    name: "${device_name} ESP Reset Reason (Raw)"
    id: esp_reset_reason_raw
    entity_category: diagnostic
    accuracy_decimals: 0
    lambda: |-
      return (float)esp_reset_reason();

  - platform: template
    name: "${device_name} WiFi Output Power Level"
    id: wifi_output_power_sensor
    unit_of_measurement: "dBm"
    accuracy_decimals: 1
    icon: "mdi:wifi-strength-outline"
    lambda: |-
      auto sel = id(wifi_power_level_select).state;
      if (!sel.empty()) {
        return std::stof(sel);
      }
      return NAN;
    update_interval: never