esphome:
  name: "esp12"
  friendly_name: esp12

#platform: wled

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "vGLe27UVLUuNsTn3YizqApfy38jpluPen6lDASE5/oY="

ota:
  - platform: esphome
    password: "ec08105588909f5108c93cea0e388255"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp11-1 Fallback Hotspot"
    password: "8tv88rqvZeqj"

captive_portal:

#wled:

#light:
#  - platform: neopixelbus
#    type: GRB
#    variant: WS2811
#    pin: GPIO2
#    num_leds: 7
#    name: "Doors-Gates Status"    

i2c:
  frequency: 150khz
  scan: true
  sda: 21
  scl: 22


#bme680_bsec:

  
sensor:
  #- platform: bme680_bsec
  
  - platform: mcp9600
    hot_junction:
     name: "Thermocouple Temperature"
     unit_of_measurement: '°F'
     accuracy_decimals: 1
    cold_junction:
      name: "Ambient Temperature"
      unit_of_measurement: '°F'
      accuracy_decimals: 1
   # address: 0x60
    update_interval: 30s
    thermocouple_type: K