esphome:
  name: esp11
  friendly_name: esp11

esp32:
  # platform: espressif32
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+l70WjRgm2+jU61MefsPeknNmnfe54RPt23tqzUOi0s="

ota:
  - platform: esphome
    password: "894a1e9ae60bca02db307c2ec412022d"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
  #- ssid: Rinard iphone
   # password: Elqt-B8ye-oe7x-qTF5
  #manual_ip:
    # Set this to the IP of the ESP
    #static_ip: 192.168.158.218
    # Set this to the IP address of the router. Often ends with .1
    #gateway: 66.234.200.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.248.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    #ssid: Rinard iphone
   # password: Elqt-B8ye-oe7x-qTF5

captive_portal:

#wled:

#light:
#  - platform: neopixelbus
#    type: GRB
#    variant: WS2811
#    pin: GPIO2
#    num_leds: 7
#    name: "Doors-Gates Status"    

i2c:
  frequency: 150000khz

#bme680_bsec:


sensor:
  #- platform: bme680_bsec
  
  #- platform: mcp9600
   # hot_junction:
    #  name: "Thermocouple Temperature"
     # unit_of_measurement: '°F'
      #accuracy_decimals: 1
    #cold_junction:
     # name: "Ambient Temperature"
      #unit_of_measurement: '°F'
    #  accuracy_decimals: 1
    #address: 0x66
    #update_interval: 30s
    #thermocouple_type: K