esphome:
  name: "esp32c3-2"
  friendly_name: ESP32C3 2
  platformio_options: #old
    board_build.flash_mode: dio #old

esp32:
  board: seeed_xiao_esp32c3 #old esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino  #old esp-idf
    # platform_version: 5.4.0 #new

# Enable logging
logger:
  hardware_uart: UART0 #new

# Enable Home Assistant API
#api:
  #encryption:
   # key: 

ota:
  - platform: esphome
    password: "7a26a2595bf09c341d8326544536f3da"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.158.206

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp32-c3-test Fallback Hotspot"
    password: "CO2ZFkd7SzgM"

captive_portal:
    
# 9nDZGhoti/A9IuD70aY2SoSyaL1NZdAIrMtRAlVqROM=



i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: bus_a
  frequency: 200kHz

# sensor:
 # - platform: aht10
 #   name: "S1 Temperature"
 #   id: temperature
  #  i2c_id: bus_a
  #  address: 0x38 # Replace with your sensor's address if different

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "FR Temperature"
      id: fr_temp_c   # <-- Assign an ID here
      unit_of_measurement: °C
    humidity:
      name: "FR Humidity"
    update_interval: 30s

# Template sensor to convert °C to °F
  - platform: template
    name: "FR Temperature (°F)"
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    lambda: |-
      if (isnan(id(fr_temp_c).state)) {
        return NAN; // Handle invalid readings
      }
      return id(fr_temp_c).state * 9.0 / 5.0 + 32.0;
    update_interval: 30s    