  # https://github.com/ApolloAutomation/TEMP_PRO-1/blob/main/Integrations/ESPHome/Core.yaml
  # https://github.com/ApolloAutomation/TEMP_PRO-1/blob/main/Integrations/ESPHome/TEMP_PRO-1_W.yaml
  # https://github.com/ApolloAutomation/TEMP_PRO-1/blob/main/Integrations/ESPHome/Battery.yaml
substitutions:
  device_name: esp32c3-2
  friendly_name: ESP32C3-2
  # api_key: "fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="
  # ota_password: "dba6cbb118b753240121b7d266f9ff56"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  platformio_options: #old
    board_build.flash_mode: dio
    board_build.mcu: esp32c3 #old
  on_boot: 
    - priority: 500 #100
      then:
        - lambda: |-
            id(deep_sleep_1).prevent_deep_sleep();
      #      id(deep_sleep_1).set_sleep_duration(id(deep_sleep_sleep_duration).state * 60 * 60 * 1000);
       # - if:
        #    condition:
         #     or:
          #      - binary_sensor.is_on: ota_mode
           #     - switch.is_on: prevent_sleep
            #then:
             # - lambda: |- 
              #    ESP_LOGW("ESP32C3-2", "Preventing Deep Sleep Due To OTA On Boot");
               #   id(deep_sleep_1).prevent_deep_sleep();
packages:
  device: !include "common/Seeed xiao ESP32-c3 base.yaml"

esp32:
  board: seeed_xiao_esp32c3 #old esp32-c3-devkitm-1
  variant: esp32c3
  # flash_size: 4MB
  # cpu_frequency: 160MHZ  
  framework:
    type: esp-idf #arduino  #old esp-idf
    # platform_version: 5.4.0 #new
    version: recommended
    #log_level: DEBUG
    #components: 
      #- name: expressif/button
      #- name: expressif/esp_lcd_touch
     # - name: johboh/homeassistantentities
      #- name: espressif/arduino-esp32
      # - name: on_client_connected
    #  - name: espressif/rgb_light
     # - name: espressif/dallas_temp
      #- name: espressif/dallas_in_range
    #  - name: max17048
      #- name: expressif/esp-idf

#external_components:
 # - source: github://Option-Zero/esphome-components
  #  components: [max17048]

#one_wire:
#  - platform: ds2484

globals:
  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'
    
# Enable logging
logger:
  hardware_uart: UART0 #new

# Enable Home Assistant API
api:
  encryption:
    key: "fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="
  reboot_timeout: 0s
  on_client_connected:
      then:
        - delay: 90s
        - if:
            condition:
              or:
                - binary_sensor.is_on: ota_mode
                - switch.is_on: prevent_sleep
            then:
              - lambda: |- 
                  ESP_LOGW("ESP32C3-2", "Preventing Deep Sleep Due To OTA Or Switch");
                  id(deep_sleep_1).prevent_deep_sleep(); 
          #  else: 
           #   - switch.turn_on: accessory_power
            #  - delay: 90s
             # - lambda: |-
              #    id(reportAllValues).execute();
            #  - delay: 90s
             # - deep_sleep.enter:
              #    id: deep_sleep_1

ota:
  - platform: esphome
    password: "dba6cbb118b753240121b7d266f9ff56"
    id: ota_esphome
  
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: false

improv_serial:

esp32_improv:
  authorizer: none

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.158.4
  power_save_mode: light
  output_power: 8.5  # Lower TX power to save battery
  id: wifi_1
  on_connect:
    - delay: 5s
    - ble.disable:
  on_disconnect:
    - ble.enable:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3-2 Fallback Hotspot"
    password: "abW2fwaqCsar"

captive_portal:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: bus_a
  frequency: 200kHz
  
# https://github.com/ApolloAutomation/TEMP_PRO-1/blob/main/Integrations/ESPHome/Core.yaml
binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  
  - platform: gpio
    pin: 
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();    
    on_release:
      then:
        - lambda: |-
            if (millis() - id(button_press_timestamp) >= 10000) {
              // Remove Wifi
              id(factory_reset_switch).turn_on();
            }
            else {
              // StatusCheck
              id(statusCheck).execute();
            }

  - platform: template
    name: Temperature Within Range
    id: temp_within_range
    lambda: 'bool temp_valid = !isnan(id(fr_temp).state); bool temp_in_range = !temp_valid || ((id(fr_temp).state <= id(max_temp).state) && (id(fr_temp).state >= id(min_temp).state)); return (temp_valid) && temp_in_range;'

  - platform: template
    name: Humidity Within Range
    id: humidity_within_range
    # Note: If additional humidity sensors are added, expand this logic following the temperature sensor pattern
    lambda: 'bool hum_valid = !isnan(id(fr_humidity).state); bool hum_in_range = !hum_valid || ((id(fr_humidity).state <= id(max_humidity).state) && (id(fr_humidity).state >= id(min_humidity).state)); return (hum_valid) && hum_in_range;'
# lambda: 'bool sht_valid = !isnan(id(sht_temperature).state); bool dallas_valid = !isnan(id(temp_probe).state); bool sht_in_range = !sht_valid || ((id(sht_temperature).state <= id(max_temp).state) && (id(sht_temperature).state >= id(min_temp).state)); bool dallas_in_range = !dallas_valid || ((id(temp_probe).state <= id(max_temp).state) && (id(temp_probe).state >= id(min_temp).state)); return (sht_valid || dallas_valid) && sht_in_range && dallas_in_range;'

  - platform: template
    name: Alarm Active
    id: alarm_active
    lambda: 'return (id(alarm_outside_temp_range).state && !id(temp_within_range).state) || (id(alarm_outside_humidity_range).state && !id(humidity_within_range).state);'
    #on_release:
     # then:
      #  - light.turn_off: rgb_light

  - platform: homeassistant
    name: "OTA Mode"
    id: ota_mode
    entity_id: input_boolean.eps32c3_2_ota_mode  #need to vreate in HA
    trigger_on_initial_state: true
      #lambda: |-
       # id(input_boolean.eps32c3_2_ota_mode).publish_state();
    on_press:
      then:
        - lambda: |- 
            id(deep_sleep_1).prevent_deep_sleep();
    on_release:  
      then:
        - if:
            condition:
              switch.is_off: prevent_sleep
            then:
              - lambda: |- 
                  id(deep_sleep_1).allow_deep_sleep();

sensor:
  - platform: aht10
    variant: AHT20
    #address: 0x28
    temperature:
      name: "FR Temperature"
      id: fr_temp   # <-- Assign an ID here
      unit_of_measurement: °F
      accuracy_decimals: 1
      filters:
       - delta: 0.5        # Only send if change > 0.5 degrees
       - heartbeat: 600s    # Force update every 10 min even if no change
       - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "FR Humidity"
      id: fr_humidity
      filters:
       - delta: 1.0        # Only send if change > 1% hum
       - heartbeat: 600s    # Force update every 10 min even if no change
    #update_interval: 60s

# ADD this instead:
  - platform: template
    name: "Wakeup Cause"
    id: wakeup_cause
    accuracy_decimals: 0
    lambda: |-
      return (int)esp_sleep_get_wakeup_cause();
  
  #- platform: uptime
   # name: "ESP Uptime"  

# https://github.com/ApolloAutomation/TEMP_PRO-1/blob/main/Integrations/ESPHome/Core.yaml
#  - platform: internal_temperature
 #   name: "ESP Temperature"
  #  id: sys_esp_temperature
   # disabled_by_default: true

  #- platform: uptime
   # name: Uptime
    #id: sys_uptime
    #update_interval: 60s

#  - platform: sht3xd
 #   id: sht30
  #  temperature:
   #   name: "SHT Temperature"
    #  id: sht_temperature
 #   humidity:
  #    name: "SHT Relative Humidity"
   #   id: sht_humidity

 # - platform: dallas_temp
  #  name: "Dallas Temperature Probe"
   # update_interval: 60s
   # id: temp_probe
   # filters:
    #  - lambda: |-
#          if (isnan(x)) {
 #           return NAN;
  #        }
#
 #         if (x == 85.0) {
  #            return NAN;
   #       }
#
 #         return x;

#  - platform: max17048
 #   id: max_17048
  #  battery_voltage:
   #   name: Battery voltage
    #  id: batt_v
#    battery_level:
 #     name: Battery level
  #    id: batt_pct
   #   filters:
    #    - lambda: |
     #       if (x > 100) return 100;
      #      else return (x);

button:
  - platform: template
    name: "Update Firmware"
    id: update_firmware
    entity_category: config
    #on_press:
     # then:
      #  - lambda: |-
       #     id(update_http_request).perform(true);
  
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    id: restart_button

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all

number:
  - platform: template
    id: min_temp
    name: Min Temperature
    min_value: -60
    max_value: 101
    step: 0.1
    unit_of_measurement: '°F'
    initial_value: 58
    optimistic: true
    update_interval: never
    mode: box
    entity_category: config

  - platform: template
    id: max_temp
    name: Max Temperature
    min_value: -60
    max_value: 100
    step: 0.1
    unit_of_measurement: '°F'
    initial_value: 80
    optimistic: true
    update_interval: never
    mode: box
    entity_category: config

  - platform: template
    id: min_humidity
    name: Min Humidity
    min_value: 0
    max_value: 100
    step: 0.1
    unit_of_measurement: '%'
    initial_value: 40
    optimistic: true
    update_interval: never
    mode: box
    entity_category: config

  - platform: template
    id: max_humidity
    name: Max Humidity
    min_value: 0
    max_value: 100
    step: 0.1
    unit_of_measurement: '%'
    initial_value: 70
    optimistic: true
    update_interval: never
    mode: box
    entity_category: config

  - platform: template
    name: "Sleep Duration"
    id: deep_sleep_sleep_duration
    min_value: 0
    max_value: 0.5
    step: 0.25
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0.25
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "h"
    on_value:
      then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(x * 60 * 60 * 1000);


switch:
#  - platform: template
 #   name: "Template Switch"
  #  id: template_sw_2
   # icon: "mdi:restart"
    #lambda: |-
     # return id(template_sw_2).state;

#    turn_on_action:
 #     - logger.log:
  #        format: "Switch Turned On!"
   #       level: DEBUG
    #      tag: main

#    turn_off_action:
 #     - logger.log:
  #        format: "Switch Turned Off!"
   #       level: DEBUG
    #      tag: main

#    disabled_by_default: false
 #   restore_mode: ALWAYS_OFF
  #  optimistic: true   # usually true for template switches
   # assumed_state: false

  - platform: factory_reset
    id: factory_reset_switch
    internal: true

  - platform: gpio
    pin: GPIO9  #7
    name: "Accessory Power"
    id: accessory_power
    restore_mode: ALWAYS_ON
    setup_priority: 1100
    internal: true

  - platform: template
    name: "Alarm Outside Temp Range"
    id: alarm_outside_temp_range    
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    
  - platform: template
    name: "Alarm Outside Humidity Range"
    id: alarm_outside_humidity_range    
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: template
    name: "Prevent Sleep"
    id: prevent_sleep
    icon: mdi:sleep
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"
    on_turn_on:
      then:
        - lambda: |- 
            id(deep_sleep_1).prevent_deep_sleep();
    on_turn_off:
      then:
        - if:
            condition:
              binary_sensor.is_off: ota_mode
            then:
              - lambda: |- 
                  id(deep_sleep_1).allow_deep_sleep();

interval:
  - interval: 10s
    id: alarm_check_interval
    startup_delay: 60s
    then:
      - script.execute: alarm_script


script:
  - id: statusCheck
    then:
      - if:
          condition:
            - lambda: 'return id(ink_ha_connected).state;'
          then:
            - logger.log: "ESP32C3-2 Automation: Connected To HA"
            #- light.turn_on: 
              #  id: rgb_light
             #   brightness: 100%
              #  red: 0%
               # green: 0%
                #blue: 100%
          else:
            - if:
                condition:
                  - wifi.connected
                then:
                  - logger.log: "ESP32C3-2 Automation: Connected To Wifi"
                 # - light.turn_on: 
                  #    id: rgb_light
                   #   brightness: 100%
                    #  red: 0%
                     # green: 100%
                      #blue: 0%
                else:
                  - logger.log: "ESP32C3-2 Automation: Not Connected To Wifi"
                  #- light.turn_on: 
                   #   id: rgb_light
                    #  brightness: 100%
                     # red: 100%
                      #green: 100%
                      #blue: 0%
      #- delay: 5s
      #- light.turn_off: rgb_light

  - id: alarm_script
    then:
    #  - if:
       # condition:
#      lambda: !lambda |-
 #       return id(alarm_active).state;

    #then:
           # - lambda: !lambda |-
            #    id(rgb_light).turn_on().set_effect("Fast Pulse").perform();
             #   id(rgb_light).turn_on().set_rgb(1, 0, 0).set_transition_length(0).perform();
              #  id(rtttl_buzzer).play("siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e;");

  - id: reportAllValues
    then:
      #- component.update: temp_probe
      #- component.update: sht30
      #- component.update: sys_esp_temperature
      #- component.update: sys_uptime
      #- component.update: max_17048
      #- script.execute: alarm_script
    

select:
      
deep_sleep:
  id: deep_sleep_1
  run_duration: 90s
  sleep_duration: 10min  
  # https://esphome.io/components/deep_sleep/

text_sensor:
  - platform: template
    name: "OTA URL"
    id: ota_url
    entity_category: "diagnostic"
    internal: true

  - platform: template
    name: "Wakeup Reason"
    lambda: |-
      switch (esp_sleep_get_wakeup_cause()) {
        case ESP_SLEEP_WAKEUP_TIMER: return {"Timer"};
        case ESP_SLEEP_WAKEUP_EXT0:  return {"EXT0"};
        case ESP_SLEEP_WAKEUP_EXT1:  return {"EXT1"};
        case ESP_SLEEP_WAKEUP_GPIO:  return {"GPIO"};
        default: return {"Other"};
      }

#0 - ESP_SLEEP_WAKEUP_UNDEFINED : In case of deep sleep, reset was not caused by exit from deep sleep
#1 - ESP_SLEEP_WAKEUP_ALL : Not a wakeup cause, used to disable all wakeup sources with esp_sleep_disable_wakeup_source
#2 - ESP_SLEEP_WAKEUP_EXT0 : Wakeup caused by external signal using RTC_IO
#3 - ESP_SLEEP_WAKEUP_EXT1 : Wakeup caused by external signal using RTC_CNTL
#4 - ESP_SLEEP_WAKEUP_TIMER : Wakeup caused by timer
#5 - ESP_SLEEP_WAKEUP_TOUCHPAD : Wakeup caused by touchpad
#6 - ESP_SLEEP_WAKEUP_ULP : Wakeup caused by ULP program
#7 - ESP_SLEEP_WAKEUP_GPIO : Wakeup caused by GPIO (light sleep only on ESP32, S2 and S3)
#8 - ESP_SLEEP_WAKEUP_UART : Wakeup caused by UART (light sleep only)
#9 - ESP_SLEEP_WAKEUP_WIFI : Wakeup caused by WIFI (light sleep only)
#10 - ESP_SLEEP_WAKEUP_COCPU : Wakeup caused by COCPU int
#11 - ESP_SLEEP_WAKEUP_COCPU_TRAP_TRIG : Wakeup caused by COCPU crash
#12 - ESP_SLEEP_WAKEUP_BT : Wakeup caused by BT (light sleep only)

# https://esphome.io/components/switch/#config-switch
# https://github.com/openairproject/sensor-esp32
# https://community.home-assistant.io/t/success-esphome-esp32-c3-bme280-mqtt-and-deep-sleep-with-homeassistant/432067

