esphome:
  name: esp32c3-4
  friendly_name: ESP32C3-4
  platformio_options: #old
    board_build.flash_mode: dio #old

esp32:
  board: seeed_xiao_esp32c3 #old esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino  #old esp-idf
    # platform_version: 5.4.0 #new

# Enable logging
logger:
  # hardware_uart: UART0 #new


# Enable Home Assistant API
api:
  encryption:
    key: "kgA37NorV4uMdsCXDydLy9a2pTHRRJdwvJ1rRPaZTfw="

ota:
  - platform: esphome
    password: "4c0e709449807decfa7b4b85c9e836d8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 192.168.158.180
  power_save_mode: light
  output_power: 8.5  # Lower TX power to save battery


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32C3-4 Fallback Hotspot"
    password: "J0jRiwyhCDDk"

captive_portal:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: bus_a
  frequency: 200kHz

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: "MBR Temperature"
      id: mbr_temp_c   # <-- Assign an ID here
      unit_of_measurement: °F
      accuracy_decimals: 1
      filters:
        - delta: 0.5        # Only send if change > 0.5 degrees
        - heartbeat: 600s    # Force update every 10 min even if no change
        - lambda: return x * (9.0/5.0) + 32.0;
    humidity:
      name: "MBR Humidity"
      filters:
        - delta: 1.0        # Only send if change > 1% hum
        - heartbeat: 600s    # Force update every 10 min even if no change
  - platform: template
    name: "Wakeup Cause"
    accuracy_decimals: 0
    lambda: return esp_sleep_get_wakeup_cause();

switch:
  - platform: template
    name: "Template Switch"
    id: template_sw_4
    icon: "mdi:restart"
    lambda: |-
      return id(template_sw_4).state;

    turn_on_action:
      - logger.log:
          format: "Switch Turned On!"
          level: DEBUG
          tag: main

    turn_off_action:
      - logger.log:
          format: "Switch Turned Off!"
          level: DEBUG
          tag: main

    disabled_by_default: false
    restore_mode: ALWAYS_OFF
    optimistic: true   # usually true for template switches
    assumed_state: false



    

# Template sensor to convert °C to °F
#  - platform: template
 #   name: "LR Temperature (°F)"
  #  unit_of_measurement: "°F"
   # accuracy_decimals: 1
    #filters:
     # - delta: 0.5        # Only send if change > 0.5 degrees
      #- heartbeat: 600s    # Force update every 10 min even if no change
#    lambda: |-
 #     if (isnan(id(lr_temp_c).state)) {
  #      return NAN; // Handle invalid readings
   #   }
    #  return id(lr_temp_c).state * 9.0 / 5.0 + 32.0;
    # update_interval: 30s    

deep_sleep:
  id: deep_sleep_4
  #run_duration: 10s
  #sleep_duration: 10min  
  # https://esphome.io/components/deep_sleep/

#0 - ESP_SLEEP_WAKEUP_UNDEFINED : In case of deep sleep, reset was not caused by exit from deep sleep
#1 - ESP_SLEEP_WAKEUP_ALL : Not a wakeup cause, used to disable all wakeup sources with esp_sleep_disable_wakeup_source
#2 - ESP_SLEEP_WAKEUP_EXT0 : Wakeup caused by external signal using RTC_IO
#3 - ESP_SLEEP_WAKEUP_EXT1 : Wakeup caused by external signal using RTC_CNTL
#4 - ESP_SLEEP_WAKEUP_TIMER : Wakeup caused by timer
#5 - ESP_SLEEP_WAKEUP_TOUCHPAD : Wakeup caused by touchpad
#6 - ESP_SLEEP_WAKEUP_ULP : Wakeup caused by ULP program
#7 - ESP_SLEEP_WAKEUP_GPIO : Wakeup caused by GPIO (light sleep only on ESP32, S2 and S3)
#8 - ESP_SLEEP_WAKEUP_UART : Wakeup caused by UART (light sleep only)
#9 - ESP_SLEEP_WAKEUP_WIFI : Wakeup caused by WIFI (light sleep only)
#10 - ESP_SLEEP_WAKEUP_COCPU : Wakeup caused by COCPU int
#11 - ESP_SLEEP_WAKEUP_COCPU_TRAP_TRIG : Wakeup caused by COCPU crash
#12 - ESP_SLEEP_WAKEUP_BT : Wakeup caused by BT (light sleep only)

# https://esphome.io/components/switch/#config-switch
# https://github.com/openairproject/sensor-esp32
# https://community.home-assistant.io/t/success-esphome-esp32-c3-bme280-mqtt-and-deep-sleep-with-homeassistant/432067

      


# Template sensor to convert °C to °F
  #- platform: template
   # name: "MBR Temperature (°F)"
    #unit_of_measurement: "°F"
    #accuracy_decimals: 1
    #filters:
    #  - delta: 0.5        # Only send if change > 0.5 degrees
     # - heartbeat: 600s    # Force update every 10 min even if no change
   # lambda: |-
    #  if (isnan(id(mbr_temp_c).state)) {
     #   return NAN; // Handle invalid readings
      #}
    #  return id(mbr_temp_c).state * 9.0 / 5.0 + 32.0;
    

