substitutions:   # Main-Seeed-Xiao-ESP32-C3.yaml
  device_name: xiao-1
  friendly_name: XIAO 1
  # api_key: "fmlpfRzTy+RXkwsNjjdKiGJDPWFKRWsqwDxk4fyAEBI="  # Commented out: Disables API encryption for testing per your request.
  ota_password: "test"  # Keep uncommented: Secure OTA password as previously agreed.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
#  ha_override_entity: input_boolean.xiao_c3_test_deep_sleep_override
#  ha_run_select: input_select.xiao_run_duration
#  ha_sleep_select: input_select.xiao_sleep_duration
#  wakeup_pin: ${wakeup_pin}  # external button
#  wakeup_pin_mode: ${wakeup_pin_mode} #
#  usb_detect_pin: ${usb_detect_pin}  # For USB power detection
#  stay_awake_pin: ${stay_awake_pin}  # For external switch
#  battery_adc_pin: ${battery_adc_pin}  # For battery voltage
#  safe_boot_pin: ${safe_boot_pin}
#  pwm_output: ${pwm_output}
#  rx_pin: ${rx_pin}
#  tx_pin: ${tx_pin}
#  miso_pin: ${miso_pin}
#  mosi_pin: ${mosi_pin}
#  sck_pin: ${sck_pin}
  run_min_initial: '240'  # Initial run min (seconds)
  sleep_dur_initial: '120'  # Initial sleep duration (seconds)
  countdown_dur: '30'  # Countdown length (seconds)

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

  on_boot:
    priority: -100
    then:
      - lambda: |-
          ESP_LOGI("boot", "[BOOT] Device booting...");
          ESP_LOGI("reset", "[BOOT] Reset reason: %d (%s)",
                   esp_reset_reason(),
                   (esp_reset_reason() == ESP_RST_POWERON) ? "Power On" :
                   (esp_reset_reason() == ESP_RST_EXT) ? "External Reset" :
                   (esp_reset_reason() == ESP_RST_SW) ? "Software Reset" :
                   (esp_reset_reason() == ESP_RST_PANIC) ? "Panic" :
                   (esp_reset_reason() == ESP_RST_INT_WDT) ? "Interrupt WDT" :
                   (esp_reset_reason() == ESP_RST_TASK_WDT) ? "Task WDT" :
                   (esp_reset_reason() == ESP_RST_WDT) ? "Other WDT" :
                   (esp_reset_reason() == ESP_RST_DEEPSLEEP) ? "Deep Sleep Wake" :
                   (esp_reset_reason() == ESP_RST_BROWNOUT) ? "Brownout" :
                   (esp_reset_reason() == ESP_RST_SDIO) ? "SDIO" : "Unknown");
          ESP_LOGI("boot", "[BOOT] Initial uptime: %.1fs", id(esp_uptime).state);
      - lambda: |-
          id(sleep_allowed) = !id(deep_sleep_override).state;  # Set based on local switch (off = allow)
          ESP_LOGI("sleep", "[BOOT] Deep sleep %s at boot (based on local override).",
                   id(sleep_allowed) ? "ALLOWED" : "PREVENTED");
      - if:
          condition:
            lambda: 'return !id(sleep_allowed);'
          then:
            - deep_sleep.prevent: deep_sleep_1
      
logger:
  level: VERBOSE #DEBUG
  baud_rate: 115200  # Change back to 0 once stable

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  # use_address: 192.168.158.180
  ap:
    ssid: "XIAO Fallback"
    password: "12345678"

  # Fallback to AP if WiFi connection fails
#   manual_ip:  # Optional for fixed IP after setup
#    static_ip: 192.168.158.180
#    gateway: 192.168.158.1
#    subnet: 255.255.255.0

  on_disconnect:
    - lambda: |-
        ESP_LOGW("wifi", "WiFi disconnected - falling back to AP mode for reprovisioning.")  

api:  # Plain API: Encryption disabled for testing.

ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

mdns:
  disabled: false

web_server:
  port: 80
  include_internal: true      

# Modular Packages
packages:
  max17048: !include packages/max17048-Seeed-Xiao-ESP32-C3.yaml #max17048 Fuel Guage
  board: !include packages/Board-Seeed-Xiao-ESP32-C3.yaml #Board specific GPIO, etc.
  base: !include packages/base.yaml  # Hardware, logger, wifi, api, ota, etc.
  sensors: !include packages/sensors.yaml  # All sensors and text_sensors
  sleep: !include packages/sleep.yaml  # Deep sleep, globals, intervals
#  ha_integration: !include packages/ha_integration.yaml  # HA binary/text sensors, switches