substitutions:
  device_name: esp32c3-2a
  friendly_name: ESP32C3-2A
  profile: balanced   # performance | balanced | saver

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 900
    then:
      - deep_sleep.prevent: deep_sleep_1
      - script.execute: boot_normal_flow
      - script.execute: apply_profile_settings

packages:
  hardware: !include packages/hardware.yaml
  wifi_ble: !include packages/wifi_ble.yaml
  globals: !include packages/globals.yaml
  sensors: !include packages/sensors.yaml
  numbers: !include packages/numbers.yaml
  switches: !include packages/switches.yaml
  alarms: !include packages/alarms.yaml
  text_sensors: !include packages/text_sensors.yaml
  diagnostics: !include packages/diagnostics.yaml

# Deep sleep engine + profiles stay here for easier debugging
script:
  - id: boot_normal_flow
    then:
      - script.execute: detect_crash_or_sleep
      - script.execute: wake_cycle
      - script.execute: evaluate_sleep_conditions

  - id: apply_profile_settings
    then:
      - lambda: |-
          std::string p = id(device_profile).state;
          if (p == "performance") {
            id(deep_sleep_run_duration).publish_state(0);
            id(deep_sleep_sleep_duration).publish_state(0);
            id(wifi_1).set_output_power(20.0f);
            id(aht20_sensor).set_update_interval(5000);
            id(active_profile).publish_state("performance");
          } else if (p == "balanced") {
            id(deep_sleep_run_duration).publish_state(120);
            id(deep_sleep_sleep_duration).publish_state(240);
            id(wifi_1).set_output_power(8.5f);
            id(aht20_sensor).set_update_interval(30000);
            id(active_profile).publish_state("balanced");
          } else if (p == "saver") {
            id(deep_sleep_run_duration).publish_state(20);
            id(deep_sleep_sleep_duration).publish_state(1800);
            id(wifi_1).set_output_power(5.0f);
            id(aht20_sensor).set_update_interval(120000);
            id(active_profile).publish_state("saver");
          }
      - script.execute: evaluate_sleep_conditions
