esphome:
  name: sensecap-d1s
  friendly_name: SenseCAP Indicator
  min_version: 2024.6.0

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0
  # level: VERY_VERBOSE

api:

ota:
  - platform: esphome
    password: "41def07295f8022fbb33225b9baa335a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SenseCAP Fallback"
    password: "1234567890"

captive_portal:

web_server:
  port: 80
  include_internal: true

# --- I2C BUS ---
i2c:
  - id: bus_a
    sda: GPIO20  #39
    scl: GPIO21  #40
    scan: true

# --- SPI BUS ---
spi:
  - id: lcd_spi
    clk_pin: GPIO41
    mosi_pin: GPIO48
    miso_pin: GPIO47

# --- PCA9554 IO EXPANDER --- 39/40
pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16

# --- RP2040 UART FOR SENSOR PACKET TRANSPORT ---
uart:
  - id: rp2040_serial
    tx_pin: GPIO17  #20
    rx_pin: GPIO16  #19
    baud_rate: 115200

# --- LVGL CORE ---
lvgl:
  buffer_size: 50%
  touchscreens:
    - my_touch

packet_transport:
  - platform: uart
    uart_id: rp2040_serial
    providers:
      - name: d1-rp2040

# --- SENSORS FROM RP2040 ---
sensor:
  - platform: packet_transport
    provider: d1-rp2040
    id: voc
    name: "VOC Index"
    internal: false
    accuracy_decimals: 0
    icon: "mdi:weather-dust"
    device_class: aqi

  - platform: packet_transport
    provider: d1-rp2040
    id: co2
    name: "CO2"
    internal: false
    accuracy_decimals: 0
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    device_class: carbon_dioxide

  - platform: packet_transport
    provider: d1-rp2040
    id: temp
    name: "Temperature"
    internal: false
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    device_class: temperature

  - platform: packet_transport
    provider: d1-rp2040
    id: humid
    name: "Humidity"
    internal: false
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    device_class: humidity

# --- INTERNAL TEMPERATURE + UPTIME ---
# sensor:
  - platform: internal_temperature
    id: internal_temp

  - platform: uptime
    id: uptime_sensor

# --- WIFI INFO FOR ADMIN PAGE ---
#wifi_info:
#  id: wifi_info

# --- BACKLIGHT CONTROL ---
output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio45
    frequency: 25000Hz

light:
  - platform: monochromatic
    id: backlight
    output: ledc_gpio45
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

# --- DISPLAY (MIPI RGB) ---
display:
  - platform: mipi_rgb
    model: SEEED-INDICATOR-D1
    id: my_display
    invert_colors: true
    update_interval: 0s
    color_order: RGB
    draw_rounding: 2
    auto_clear_enabled: false
    use_axis_flips: true

# --- TOUCHSCREEN (FT5x06) ---
touchscreen:
  - platform: ft5x06
    id: my_touch
    transform:
      mirror_x: true
      mirror_y: true
    on_touch:
      then:
        - if:
            condition: lvgl.is_paused
            then:
              - lvgl.resume:
              - light.turn_on: backlight
              - lvgl.page.show: # page_home
                  id: page_home

# --- GLOBALS FOR MIN/MAX ---
globals:
  - id: temp_min
    type: float
    initial_value: "9999"
  - id: temp_max
    type: float
    initial_value: "-9999"

  - id: humid_min
    type: float
    initial_value: "9999"
  - id: humid_max
    type: float
    initial_value: "-9999"

  - id: co2_min
    type: float
    initial_value: "9999"
  - id: co2_max
    type: float
    initial_value: "-9999"

  - id: voc_min
    type: float
    initial_value: "9999"
  - id: voc_max
    type: float
    initial_value: "-9999"

# --- TIME (REQUIRED FOR CLOCKS) ---
time:
  - platform: homeassistant
    id: ha_time

# --- MODULAR UI SYSTEM ---
packages:
  - !include sensecap-ha/esphome/ui/ui_theme.yaml
  - !include sensecap-ha/esphome/ui/ui_home.yaml
#  - !include sensecap-ha/esphome/ui/ui_graphs.yaml
  - !include sensecap-ha/esphome/ui/ui_air.yaml
  - !include sensecap-ha/esphome/ui/ui_settings.yaml
#  - !include sensecap-ha/esphome/ui/ui_admin.yaml
  - !include sensecap-ha/esphome/ui/ui_navigation.yaml
#  - !include sensecap-ha/esphome/ui/ui_updates.yaml
  - !include sensecap-ha/esphome/ui/ui_sleep.yaml
  - !include sensecap-ha/esphome/ui/ui_analog_clock.yaml
