esphome:
  name: sensecap-d1s
  friendly_name: SenseCAP Indicator
  min_version: 2024.6.0
  on_boot:
    priority: -100.0  # High priority to run after LVGL init
    then:
      - delay: 5s  # Show boot for 5s
      - lvgl.page.show: main_page  # Switch to dashboard

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework: 
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz
    
logger:
  hardware_uart: UART0

api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "SenseCAP Fallback"
    password: "fallback_pass"

captive_portal:

i2c:
  - id: bus_a
    sda: GPIO39
    scl: GPIO40
    scan: false

pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16

uart:
  - id: rp2040_serial
    tx_pin: GPIO20
    rx_pin: GPIO19
    baud_rate: 115200

packet_transport:
  - platform: uart
    uart_id: rp2040_serial
    providers:
      - name: d1-rp2040    

sensor:
  - platform: packet_transport
    provider: d1-rp2040
    id: voc
    name: "VOC Index"
    internal: False
    accuracy_decimals: 0
    icon: "mdi:weather-dust"
    device_class: aqi
  - platform: packet_transport
    provider: d1-rp2040
    id: co2
    name: "CO2"
    internal: False
    accuracy_decimals: 0
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    device_class: carbon_dioxide
  - platform: packet_transport
    provider: d1-rp2040
    id: temp
    name: "Temperature"
    internal: False
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    device_class: temperature
  - platform: packet_transport
    provider: d1-rp2040
    id: humid
    name: "Humidity"
    internal: False
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    device_class: humidity

output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio45
    frequency: 100Hz

light:
  - platform: monochromatic
    name: "Backlight"
    id: backlight
    output: ledc_gpio45
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

display:
  - platform: mipi_rgb
    model: SEEED-INDICATOR-D1
    id: my_display
    lambda: |-
      it.print(240, 240, id(arial24), TextAlign::CENTER, "Hello David!");

touchscreen:
  - platform: ft5x06
    id: my_touch
    transform:
      mirror_x: true
      mirror_y: true
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: backlight

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touch
  on_idle:
    timeout: !lambda |-
      return 10000;  # 10s idle (in ms)
    then:
      - light.turn_off: backlight
      - lvgl.pause:
  pages:
    - id: boot_page
      widgets:
        - obj:
            id: boot_screen
            x: 0
            y: 0
            width: 100%
            height: 100%
            bg_color: 0xffffff
            bg_opa: COVER
            radius: 0
            pad_all: 0
            border_width: 0
            widgets:
              - image:
                  align: CENTER
                  src: boot_logo
                  y: -40
              - spinner:
                  align: CENTER
                  y: 95
                  height: 50
                  width: 50
                  spin_time: 1s
                  arc_length: 60deg
                  arc_width: 8
                  indicator:
                    arc_color: 0x18bcf2
                    arc_width: 8
    - id: main_page
      widgets:
        - label:
            id: clock_label
            text: !lambda |-
              auto time = id(ha_time).now();
              return time.strftime("%I:%M %p");
            text_font: arial24
            align: center
              
interval:
  - interval: 1s
    then:
      - lvgl.widget.refresh: clock_label

time:
  - platform: homeassistant
    id: ha_time

packages:
  - !include iaq-project/packages/display-fonts.yaml

image:
  - file: https://esphome.io/favicon-512x512.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: alpha_channel

# homeassistant: {}