esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  on_boot:
    priority: -100
    then:
      - script.execute: boot_orchestrator

logger:
  hardware_uart: UART0
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_ap_password

captive_portal:

web_server:
  port: 80
  include_internal: true

safe_mode:
  disabled: false
