# PMS7003 - 
# PMS7003 TX (SEND) → Xiao RX (GPIO20/D7/UART0_RX)
# PMS7003 RX (RECEIVE) → Xiao TX (GPIO21/D6/UART0_TX)  # Optional for passive mode, but include it
# PMS7003 VCC → 5V (if available) or 3.3V (check sensor specs; PMS7003 typically needs 5V)
# PMS7003 GND → GND
packages:
  board: !include Board-Seeed-Xiao-ESP32-C3.yaml  # Nested package for board-specific pinouts (e.g., I2C pins)

uart:
  - id: uart_bus
    rx_pin: ${rx_pin}  # D7/RX
    tx_pin: ${tx_pin}  # D6/TX (optional but recommended)
    baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003  # For PMS7003
    uart_id: uart_bus
    update_interval: 120s  # Optional: Adjust for sensor longevity (e.g., 120s to reduce fan wear)
    pm_1_0:
      name: "${device_name} PM1.0"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 0
    pm_2_5:
      name: "${device_name} PM2.5"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 0
    pm_10_0:
      name: "${device_name} PM10"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 0