time:
  - platform: homeassistant
    id: ha_time

binary_sensor:
  - platform: homeassistant
    id: ha_cleaners_toggle
    entity_id: input_boolean.cleaners_toggle
    internal: true
  - platform: homeassistant
    id: ha_dani_mode_on
    entity_id: input_boolean.dani_mode_on
    internal: true
  - platform: homeassistant
    id: ha_front_door_auto_lock_off
    entity_id: input_boolean.front_door_auto_lock_off
    internal: true
  - platform: homeassistant
    id: ha_tod_control
    entity_id: input_boolean.automation_time_of_day_trigger
    internal: true
  - platform: homeassistant
    id: ha_motion_automation_off
    entity_id: input_boolean.motion_automation_off
    internal: true
  - platform: homeassistant
    id: ha_entry_motion_automation_off
    entity_id: input_boolean.entry_motion_automation_off
    internal: true
  - platform: homeassistant
    id: ha_garage_light_automation_off
    entity_id: input_boolean.garage_light_automation_off
    internal: true
  - platform: homeassistant
    id: ha_mbr_motion_off
    entity_id: input_boolean.mbr_motion_off
    internal: true
  - platform: homeassistant
    id: ha_attic_fan_on
    entity_id: switch.attic_fan
    internal: true
  - platform: homeassistant
    id: ha_attic_fan2_on
    entity_id: switch.attic_fan_2
    internal: true
  - platform: homeassistant
    id: ha_fr_fan_on
    entity_id: fan.in_wall_fan_speed_control_500s
    internal: true
  - platform: homeassistant
    id: ha_mbr_fan_on
    entity_id: fan.mbr_fan_light
    internal: true
  - platform: homeassistant
    id: ha_all_lights_toggle
    entity_id: input_boolean.all_lights_toggle
    internal: true
  - platform: homeassistant
    id: ha_outdoor_lights_toggle
    entity_id: input_boolean.outdoor_lights_toggle
    internal: true
  - platform: homeassistant
    id: ha_mbr_lights_on
    entity_id: light.mbr_lights
    internal: true
  - platform: homeassistant
    id: ha_fr_lights_on
    entity_id: light.in_wall_paddle_dimmer_500s
    internal: true
  - platform: homeassistant
    id: ha_library_lights_on
    entity_id: light.library_lights
    internal: true
  - platform: homeassistant
    id: ha_living_room_lights_on
    entity_id: light.living_room_lights
    internal: true

sensor:
  - platform: homeassistant
    id: ha_fr_fan_pct
    entity_id: fan.in_wall_fan_speed_control_500s
    attribute: percentage
    internal: true
  - platform: homeassistant
    id: ha_mbr_fan_pct
    entity_id: fan.mbr_fan_light
    attribute: percentage
    internal: true
  - platform: homeassistant
    id: ha_fr_lights_brightness
    entity_id: light.in_wall_paddle_dimmer_500s
    attribute: brightness
    internal: true

  - platform: template
    id: ha_tstat_current_temp
    internal: true
    update_interval: never
    lambda: |-
      std::string s = id(ha_tstat_current_temp_txt).state;
      if (s.empty() || s == "None" || s == "none" || s == "unknown" || s == "unavailable") return NAN;
      return atof(s.c_str());

  - platform: template
    id: ha_tstat_target_temp
    internal: true
    update_interval: never
    lambda: |-
      static float last_valid = 68.0f;
      std::string s = id(ha_tstat_target_temp_txt).state;
      if (s.empty() || s == "None" || s == "none" || s == "unknown" || s == "unavailable") return last_valid;
      float v = atof(s.c_str());
      if (isnan(v)) return last_valid;
      static std::string last_bad;
      if (v < 50.0f || v > 85.0f) {
        if (s != last_bad) {
          ESP_LOGW("tstat_sync", "Ignoring out-of-range target temp %.1f from HA text state '%s'", v, s.c_str());
          last_bad = s;
        }
        return last_valid;
      }
      last_bad.clear();
      last_valid = v;
      return v;

text_sensor:
  - platform: homeassistant
    id: ha_mbr_fan_dir
    entity_id: fan.mbr_fan_light
    attribute: direction
    internal: true
  - platform: homeassistant
    id: ha_mbr_lights_brightness_txt
    entity_id: light.mbr_lights
    attribute: brightness
    internal: true
  - platform: homeassistant
    id: ha_library_lights_brightness_txt
    entity_id: light.library_lights
    attribute: brightness
    internal: true
  - platform: homeassistant
    id: ha_living_room_lights_brightness_txt
    entity_id: light.living_room_lights
    attribute: brightness
    internal: true
  - platform: homeassistant
    id: ha_front_door_lock_state
    entity_id: lock.front_door_lock
    internal: true

  - platform: homeassistant
    id: ha_tstat_mode
    entity_id: climate.thermostat
    internal: true
  - platform: homeassistant
    id: ha_tstat_hvac_action
    entity_id: climate.thermostat
    attribute: hvac_action
    internal: true
  - platform: homeassistant
    id: ha_tstat_current_temp_txt
    entity_id: climate.thermostat
    attribute: current_temperature
    internal: true
  - platform: homeassistant
    id: ha_tstat_target_temp_txt
    entity_id: climate.thermostat
    attribute: temperature
    internal: true
  - platform: homeassistant
    id: ha_tstat_fan_mode
    entity_id: climate.thermostat
    attribute: fan_mode
    internal: true
  - platform: homeassistant
    id: ha_tstat_fan_state
    entity_id: climate.thermostat
    attribute: fan_state
    internal: true

