esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  on_boot:
    priority: -100
    then:
      - script.execute: boot_orchestrator

logger:
  hardware_uart: UART0
  level: DEBUG

api:

ota:
  - platform: esphome
    password: "41def07295f8022fbb33225b9baa335a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fallback AP"
    password: "1234567890"

captive_portal:

web_server:
  port: 80
  include_internal: true

safe_mode:
  disabled: false

switch:
  - platform: restart
    id: restart_switch
    name: "Restart Device"

  - platform: factory_reset
    id: factory_reset_switch
    name: "Factory Reset Device"
